version: 2
updates:
  - package-ecosystem: uv
    directory: /adapter
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: /vpl
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: /voice
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
